config/routes.rb
Rails.application.routes.draw do

  concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
  mount Blacklight::Engine => '/'
  mount BlacklightAdvancedSearch::Engine => '/'

  concern :searchable, Blacklight::Routes::Searchable.new

  resource :catalog, only: [:index], as: 'catalog', path: '/catalog', controller: 'catalog' do
    concerns :searchable
    concerns :range_searchable
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  mount CurationConcerns::Engine, at: '/'
  resources :welcome, only: 'index'
  root 'welcome#index'
  curation_concerns_collections
  curation_concerns_basic_routes
  curation_concerns_embargo_management
  concern :exportable, Blacklight::Routes::Exportable.new

  resources :solr_documents, only: [:show], path: '/catalog', controller: 'catalog' do
    concerns :exportable
  end

  resources :bookmarks do
    concerns :exportable

    collection do
      delete 'clear'
    end
  end

  get '/concern/file_sets/:id/file_status' => 'curation_concerns/file_sets#file_status', as: :file_status_curation_concerns_file_set
  get '/concern/file_sets/:id/stage' => 'curation_concerns/file_sets#stage', as: :stage_curation_concerns_file_set
  get '/concern/file_sets/:id/unstage' => 'curation_concerns/file_sets#unstage', as: :unstage_curation_concerns_file_set
  get '/concern/file_sets/:id/fixity' => 'curation_concerns/file_sets#fixity', as: :fixity_curation_concerns_file_set

end

app/views/advanced/_advanced_search_form.html.erb
  <% unless (search_context_str = render_search_to_s( advanced_search_context)).blank? %>
    <div class="constraints well search_history">
      <h4><%= t 'blacklight_advanced_search.form.search_context' %></h4>
      <%= search_context_str %>
    </div>
  <% end %>

<%= form_tag search_catalog_path, :class => 'advanced form-horizontal', :method => :get do  %>

  <%= render_hash_as_hidden_fields(search_state.params_for_search(advanced_search_context)) %>

  <div class="input-criteria">

      <div class="query-criteria">
        <h3 class="query-criteria-heading">
          <%= t('blacklight_advanced_search.form.query_criteria_heading_html', :select_menu =>  select_menu_for_field_operator ) %> 
        </h3>

        <div id="advanced_search">
          <%= render 'advanced/advanced_search_fields' %>
          <%= render 'advanced_search_ranges' %>
        </div>


      </div>
      
      <div class="limit-criteria">
        <h3 class="limit-criteria-heading"><%= t('blacklight_advanced_search.form.limit_criteria_heading_html')%></h3>

        <div id="advanced_search_facets" class="limit_input">
          <% if blacklight_config.try(:advanced_search).try {|h| h[:form_facet_partial] } %>
            <%= render blacklight_config.advanced_search[:form_facet_partial] %>
          <% else %>
            <%= render 'advanced_search_facets' %>
          <% end %>
        </div>


      </div>
  </div>

  <hr>

  <div class="sort-submit-buttons clearfix">
    <%= render 'advanced_search_submit_btns' %>
  </div>

<% end %>

app/views/advanced/_advanced_search_ranges.html.erb
<div class="form-group advanced-search-facet">
  <%= label_tag "filesize", :class => "col-sm-3 control-label" do %>
      Filesize (bytes)
  <% end %>

  <div class="col-sm-4">
    <%= render_range_input("file_size_ltsi", :begin, 'Filesize', 16) %>
  </div>
  <div class="col-sm-1">
    &nbsp;-&nbsp;
  </div>
  <div class="col-sm-4">
    <%= render_range_input("file_size_ltsi", :end, 'Filesize', 16) %>
  </div>
</div>

<div class="form-group advanced-search-facet">
  <%= label_tag "mdpi_date", :class => "col-sm-3 control-label" do %>
      MDPI Timestamp (yyyymmdd)
  <% end %>

  <div class="col-sm-4">
    <%= render_range_input("mdpi_timestamp_isi", :begin, 'MDPI Date', 8) %>
  </div>
  <div class="col-sm-1">
    &nbsp;-&nbsp;
  </div>
  <div class="col-sm-4">
    <%= render_range_input("mdpi_timestamp_isi", :end, 'MDPI Date', 8) %>
  </div>
</div>